version: '3.3'
services:
  db:
    image: mysql:latest
    container_name: mysql
    restart: always
    env_file: 
      - .env
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./sql/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - my-db:/var/lib/mysql
  website:
    image: ghcr.io/patricklaabs/abdb:0.0.2
    restart: always
    env_file: 
      - .env
    ports:
      - '8080:8080'
    volumes: 
      - ./templates/:/templates/
volumes:
  my-db: