version: '3.3'
services:
  db:
    image: mysql:latest
    restart: always
    env_file: 
      - .env
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./sql/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - my-db:/var/lib/mysql
volumes:
  my-db: