version: '3.5'
services:
  db:
    image: mysql:latest
    container_name: mysql
    restart: always
    networks: 
      - nets
    ports: 
      - 3306:3306
    expose: 
      - '3306'
    env_file: 
      - ../.env
    volumes:
      - .././sql/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - my-db:/var/lib/mysql
volumes:
  my-db:
networks: 
  nets:
    driver: bridge